app/scripts/views/fields/field-view.js
Clicking a field's label to copy it's value is a super-convenient feature.  In the browser, this works flawlessly, even for values with more than one line.  In the desktop client, however, copying a multi-line field in this way will copy the field's value, but with all of the lines concatenated.  In other words, if a field's value was:
```
one
two
three
```
Clicking on the field's name would copy the text above if Keeweb is loaded up in a browser, but when it's run as an Electron app, the following is copied:
```
onetwothree
```
Although it's a non-standard property of DOM `Node`s, the `innerText` property is documented as preserving newlines.
BTW, I was going to submit the PR against `master`, but I get build errors against that branch...the `develop` branch builds fine :).  Guess …
=> Try harder to to preserve newlines while copying in the Desktop app

.github/ISSUE_TEMPLATE.md
The template wasn't updated to point to the new Github org, so following the link wouldn't work anymore when people submit images.
=> Updated ISSUE_TEMPLATE: point antelle -> keeweb org

app/styles/areas/_list.scss
When downloading favicons or setting custom icons, they were 2px too wide.
**Before:**
**Now:**
=> Fix favicons and images from being stretched horizontally

app/scripts/storage/storage-webdav.js
Modified WebDav save move destination to work correctly with relative and root paths, removing any URL parameters to prevent replacing the wrong /, fixes #435
=> Fixed WebDav save destination

app/scripts/comp/launcher-electron.js
I was getting an error when running the project through electron:
> Error Helper not found. Searched paths: ... (error stems from auto-type-native-helper.js)
I believe the issue is caused by the call to Launcher.statFileSync(possiblePath) on line 22. Looking at the method implementation (in launcher-electron.js, line 78), it returns undefined, yet AutoTypeNativeHelper tries to get a ctime property from it.
=> KeeWeb helper not found

package/docker-rpi/Dockerfile, package/docker-rpi/LICENSE, package/docker-rpi/entrypoint.sh, package/docker-rpi/keeweb.conf
I implemented support to run the Docker image on a raspberry pi (armhf-based). I tried to keep it as close to possible to your original Dockerfile and therefore kept installing nginx (as there is no official armhf nginx package) and installing the rest in to separate RUNs. I also had to change the way how daemon off is set in nginx as your sed didn't work for me (there is no pid directive in the standard conf). Lastly I moved the entrypoint copy closer to the end as I played a lot with that script and docker build now only needs to change a few layers in the end if you change that file instead of always downloading from github
=> implement Docker support on raspberry pi

desktop/app.js
Fixes the scaling error reported in #531, caused by some issue with Electron and setting the icon on BrowserWindow on win32.
Instead, if we leave it out like I did now, it will use the icon for the Electron executable currently defined in the Gruntfile.
See https://github.com/atom/atom/issues/4811 for reference.
Current screenshot of result after packaging:
Warning regards testing/validation: This will result in the default Atom icon being displayed when not actually packaging the electron app, e.g. when running 'npm run-script electron'
=> Fixes #531: Window icon scaling error on win32 Electron app

desktop/app.js
On Windows 7, this corrects the issue described in Issue #978.
Commit https://github.com/keeweb/keeweb/commit/d76cc891e17c93efc2b52de37db69bb28fd37792 broke minimize to tray on Windows: the tray icon appeared, but the window didn’t go away. This fixes that problem as well. The error appeared to be a result of a simple omission in the `minimizeApp` function when the Darwin and non-Darwin code paths were split; `MainWindow.minimize();` was left out of the non-Darwin path. The fix for both issues is to replace `MainWindow.minimize();` and `mainWindow.setSkipTaskbar(true);` with `mainWindow.hide();` in the non-Darwin path, and to replace `mainWindow.focus();` with `mainWindow.show();` in the `restoreMainWindow` function. This produces expected Windows behavior.
I have no way of testing this …
=> Proper minimize to tray for Windows (and Linux?)

app/scripts/views/app-view.js, app/scripts/views/details/details-view.js, app/scripts/views/fields/field-view.js, app/scripts/views/menu/menu-item-view.js, app/scripts/views/open-view.js, app/styles/areas/_details.scss, app/templates/details/field.hbs
This implements the change requested in #970 by allowing field labels in the details view to be dragged. The value dragged is the same as the value copied to the clipboard by clicking on the label.
In testing I saw that as soon as the label began dragging, the “drop attachments here” message replaced the details view. While this didn’t interfere with dragging the field, it was somewhat jarring and unexpected.
Further investigation showed that in many places KeeWeb indicates that it is possible to drop something without first checking what is being dragged. https://github.com/keeweb/keeweb/commit/7a3cc9c863ce4a8460e83d925225638a97b53ea4 limits the “drop attachments here” message to appear only when a *file* is dragged across the details view. …
=> Draggable field labels

desktop/app.js
I believe this will fix [#877 Issue with WebDav](https://github.com/keeweb/keeweb/issues/877).
It does need more testing than I can give it. It appears to make my OwnCloud installation work with KeeWeb, and it doesn’t appear to interfere with access to Google Drive. The changes are all in desktop/app.js, so the web version isn’t affected at all.
The underlying problem is that Chromium sends a mal-formed Origin header when it sees a PUT XMLHttpRequest from a local file. (Chromium sends `Origin: file://`; per [rfc6454](https://tools.ietf.org/html/rfc6454#section-7), only scheme://host and scheme://host:port are valid; if the origin does not have a scheme and a host, the literal value `none` must be used if the Origin header is supplied.)
The Origin header is supplied by the browser and …
=> Fix for Issue #877 - remove bad Origin header

desktop/app.js
This fixes issue #807 on Windows 7 and presumably elsewhere. All that was wrong is that we were checking for a previous instance in the app.on('ready') handler. We need to check in code that runs before that event gets raised.
=> Fix Issue #807 - single instance not enforced

app/styles/areas/_details.scss
Fix various glitches in details panel layout:
* Make long Website fields have the same width as other fields, and leave more than a sliver of space at the end in which to click to edit.
* Let the attachment download/delete instructions wrap if they are too long to fit on one line.
* Make fields in the history wrap the same way they do in the ordinary details pane (fixes #945).
* Avoid having the navigation area and the top of the history details overlap when the window height is too small to show everything without scrolling.
* Align the right edges of the history navigation area and the revert/delete buttons so that they don't overlap the scroll bar.
=> Adjust some overflow behavior in the details panel, includes fixing Issue #945

app/scripts/comp/launcher-electron.js, desktop/app.js
The fix for alt-tab behavior when KeeWeb is minimized to the tray in 3dae878 left a problem when auto-type raises a selection list: the taskbar button shows, and after a selection is made KeeWeb minimizes
to the taskbar but leaves a tray icon present. The same thing happens if auto-type is canceled by clicking either the minimize button or the close button at the top right of the selection window. From this state, various scenarios lead to having duplicate tray icons.
This fix restores the behavior of 1.6.3 when auto-type raises a selection list while KeeWeb is minimized to the tray: the selection window shows, the tray icon stays, and no taskbar button shows.
There remains a case which is not handled perfectly: when KeeWeb is minimized to the tray, auto-type raises a selection list, and …
=> tray-min-auto-type-select-fix

app/scripts/models/app-model.js, app/scripts/views/list-search-view.js
In [this issue](https://github.com/keeweb/keeweb/issues/231) we had a discussion with @antelle about the ability customize default advancedSearch in json settings.
I've implemented this feature.
Add advancedSearch to your settings.json like this
```
{
"settings": {
...
},
"advancedSearch": {
"user": false,
"other": true,
"url": true,
"protect": false,
"notes": true,
"pass": false,
"cs": false,
"regex": false,
"history": false,
"title": true
},
"showOnlyFilesFromConfig": false
}
```
and this filters will be activated by default instead of hard-coded ones.
=> Allow custom default advancedSearch filters in settings json

app/scripts/models/app-model.js
Related to ["Allow custom default advancedSearch filters in settings json" pull request](https://github.com/keeweb/keeweb/pull/1061).
=> Fix: search filters UI opens when user clicks on folder with adancedSearch set in config.json

Gruntfile.js
I just modified the webpack config for the dev-server to use non-minified versions of libraries to allow for better debugging and thought I'd share. 😉
=> Use non-minified versions of depending libraries on dev-server

app/scripts/views/fields/field-view-custom.js, app/styles/areas/_menu.scss
Fixes #791 for both mentioned issues there.
I implemented removing a custom field by emptying its title. Currently, this was only possible by emptying its value, which broke templates support. However, this introduces some kind of breaking change. Should I narrow this implementation so it only works for templates?
=> Remove a custom field from a template, better drag and drop visibility when moving folders

desktop/app.js
I realized close window shortcut doesn't work on Mac, therefore I added this item to menu.
=> Add close window item to menu on Mac

README.md, dev-env.sh
BTW, instead of cloning keeweb twice add a git-worktree for the gh-pages.
Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>
=> dev-env.sh: allow to clone via http url

dev-env.sh
It's what will work for the most of users.
Suggested-by: @antelle
Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>
=> dev-env.sh: use HTTP schema as default for cloning

app/scripts/auto-type/index.js, app/scripts/locales/base.json, app/scripts/models/app-settings-model.js, app/scripts/views/settings/settings-general-view.js, app/templates/settings/settings-general.hbs, package-lock.json
In this PR I implemented a setting to disable the direct run of Autotype if one specific entry can be found.
This is something I need in connection to the feature of specifically entering only the password or username using Autotype.
The default value of this setting is *true*, which mimics the current behavior, so this is backwards compatible and should be valid for a minor version bump.
=> New Feature: Disable direct autotype

app/scripts/util/comparators.js
Fixes #1147 
The only risks I see are:
1) If a user has an "Invalid Character" in their titles (or other strings compared by this function) the sort order will change.
2) If other JS runtimes perform a comparison using UTF32 characters.
(1) Seems irrelevant; Unlikely such characters have any benefit for users and may cause a whole host of other problems in KeeWeb other kdbx-based apps anyway.
(2) Seems unlikely since the fromCharCode spec only accepts UTF16 characters so any deviation is likely to be a significant bug in those runtimes. At least the behaviour of `0xffff` is identical to `0xffffffff` in Chromium and Firefox.
I've tested a fixed version (via Kee Vault) in Edge, Chrome and Firefox. Happy to test on my Windows machine using the KeeWeb beta site when the fix is merged, …
=> Change string comparator last char value to 0xfffd

app/scripts/models/file-model.js
* Makes the list of entries to delete immutable to ensure all are moved to the null group
* Resets model items to ensure view shows that groups and their contents have been deleted
Tested in Kee Vault on Firefox and Chrome
=> Improve reliability of emptying trash

app/scripts/views/details/details-view.js
This fixes a bug in Chrome where the "View Source" feature is invoked when attempting to copy the URL value via Ctrl+U (at least on Linux Chromium).
I've applied the same change to C and B for consistency and future-proofing, although I see no current bugs caused by the existing behaviour of allowing the events to attempt their default actions (presumably they are a noop in most browsers since no text is selected at the time).
Tested in browsers but not electron.
=> Prevent default on details copy keyboard shortcuts

app/scripts/util/data/otp.js
I extracted the "formatting" section of Otp.prototype.next into a separate function, and added a new formatter for Steam-issued TOTP URLs
=> Added Steam TOTP output format

app/index.html
the meta tag:
`<meta name="apple-mobile-web-app-capable" content="yes" />`
was appearing twice
=> remove duplicate apple-mobile-web-app-capable meta tag

.prettierrc, Gruntfile.js, README.md, build/webpack.config.js, package-lock.json, package.json
As the title suggests, it looks like this was once working but presumably Windows got left behind at some point 😄 
- Configured line ending settings in the Prettier config to "auto"
- Without this, Prettier wants to convert everything to Unix line endings because it inherits that config from the `.editorconfig` - this causes linting to fail and therefore the `npm run dev` command doesn't work. The downside to this is that Prettier will no longer ensure all files use Unix line endings (it will only ensure that line endings are consistent within a file).
- Since the repository doesn't include a `.gitattributes` file, files are checked out on Windows with CRLF line endings by default. However, any commits made on Windows will convert those files back to Unix (LF) line endings for git's …
=> Add support for building KeeWeb on Windows

app/manifest/manifest.json
In order to be installable as PWA, the app should have at least **start_url** property in the manifest.
To address https://github.com/keeweb/keeweb/issues/1360#issuecomment-582912644
Also checked with Lighthouse audit, no PWA blocking issues found.
=> Make the app installable as PWA

package/docker/Dockerfile
Source: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
=> Fix: MAINTAINER directive in Dockerfile is deprecated

desktop/app.js
`npm run electron` throws an error on linux/windows, this is due to calling app.dock.setIcon() without checking for the platform first (Native to darwin, all other occurrences of app.dock check for platform first).
Here is the original error message:
> TypeError: Cannot read property 'setIcon' of undefined
>     at setDevAppIcon (C:\Users\Benjamin\Desktop\keeweb\desktop\app.js:616:18)
>     at Object.<anonymous> (C:\Users\Benjamin\Desktop\keeweb\desktop\app.js:64:1)
>     at Module._compile (internal/modules/cjs/loader.js:968:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
>     at Module.load (internal/modules/cjs/loader.js:816:32)
>     at Module._load (internal/modules/cjs/loader.js:728:14)
>     at Module._load (electron/js2c/asar.js:717:26)
>     at …
=> Added check for platform before calling app.dock

package/docker-rpi/Dockerfile, package/docker/Dockerfile
Reference:
- docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
> For other items (files, directories) that do not require ADD’s tar auto-extraction capability, you should always use COPY.
=> Clean up apt local cache in Dockerfile

.github/workflows/build.yaml
As you can see in https://hub.docker.com/r/antelle/keeweb/tags?page=1&ordering=last_updated, tagged releases are not pushed since >3 months now. This fix will restore the functionality.
=> fix(docker): publish all docker image tags

app/scripts/views/settings/settings-browser-view.js
Firstly - love the new KeeWeb Connect extension - awesome work 👍 
I noted under https://app.keeweb.info/ - the link to take the user to the extension download pages for each browser type (Chrome/Firefox/etc.) is currently broken with a blank `href=""`. Digging in, noted the `const/Links` property it's after is incorrect. This fixes that behaviour.
=> Fix broken links to download the KeeWeb Connect browser extension

app/content/oauth-result/teams.html, app/scripts/const/default-app-settings.js, app/scripts/locales/base.json, app/scripts/storage/impl/storage-onedrive.js, app/scripts/storage/impl/storage-teams.js, app/scripts/storage/index.js, app/styles/base/_icon-font.scss
- added teams storage
- added tenant id configuration for onedrive and teams
The code was tested to browse and open. Haven't tested to write.
Linked to issue #1265 
Adds new requirements to the Azure Active Directory Configuration:
- Permission:
- Sites.ReadWrite.All
- Team.ReadBasic.All
- Redirect URL:
- https://HOSTNAME/oauth-result/teams.html (MUST ALSO BE ADDED TO THE SHARED TENANT)
Known issues:
- not able to return to the list of Teams
- Code could be merged with onedrive once the API is the same but would need some abstraction.
=> added teams storage; added tenant id configuration for microsot

package/deb/usr/bin/keeweb
These two flags tell Electron, through Chromium, to use Wayland for rendering. The flags are set in the bash script, because setting them in desktop/main.js causes issues with rendering.
Rendering with Wayland instead of X11 and XWayland gives better support for DPI scaling. Additionally, this change also has implications for drag-and-drop, since drag-and-drop does not work consistently from XWayland to Wayland apps and visa versa (for example, from XWayland KeeWeb to Wayland Firefox under sway).
=> Use Wayland backend for Wayland sessions

app/scripts/models/file-model.js
This fixes the issue #1924
So as kdbxweb has protected property `keyFileHash` in credentials, it must not been set to null without setter.
=> Fix remove key file

app/scripts/models/file-model.js
This PR addresses the issue with users not being able to unassign a keyfile once a vault has been created with one.
- #2073
- #1924 
- #2038 
- #1941
=> fix: addresses not being able to unset a keyfile once added to a vault

app/scripts/models/entry-model.js, app/scripts/util/data/otp.js
Addresses issue with being unable to use otpauth url `otpauth://totp?secret=`
Patch allows for otpauth urls to be structured as:
- `otpauth://totp?secret=`
- `otpauth://totp/default?secret=`
<br />
- #2145
=> fix: support multiple otpauth url structures

app/scripts/util/formatting/password-presenter.js
This fix applies to the **Reveal Password** button.
Converts spaces and a few other characters empty characters into non-breaking spaces so that they'll render properly in the password field.
=> fix: convert space character to non-breaking space on password reveal

app/scripts/util/data/csv-parser.js
Thanks for taking the time to contribute! :gift:
I have fixed the issue with CSV import ignoring the last entry as mentioned in issue (#1904). This bug was there because the parse method in csv-parser method was using (<) condition instead of (<=) that's why the last line is always ignored. So I fixed it by updating the check condition.
=> Fixed issue with Csv parser parse (#1904)

desktop/scripts/const/extension-ids.js
We are changing the UUID since we don't have access to the closed account or now revoked add-on so we need to use a new UUID for native messaging.
See https://github.com/keeweb/keeweb-connect/pull/55
=> Update to new UUID for firefox extension

app/scripts/storage/impl/storage-gdrive.js
We need to downgrade the google drive scope to drive.file, which allows keeweb to continue working without requiring any sort of extensive auditing verification from google.
I've tested this locally and it works fine, but we'll need to update the scope in the google drive api project as well to get this working
**Note**:
I just saw the note saying to use develop for normal features and master for hotfixes. This one is on master, but I think thats appropriate since this is an ugly little anti-feature that prevents usage of google drive. 
Hope this is ok, thanks!
=> Hotfix: Downgrade gdrive scope to drive.file
