README.md
fixed some broken links in the readme.
=> Fix broken links to antelle/keeweb

app/scripts/models/entry-model.js
Some websites (google) give you the key separated with spaces
This try to remove spaces and see if it is a valid Otp.
=> One time password with spaces

.editorconfig
Removing extra charset setting in EditorConfig to help keep the code fresh and healthy.
=> Remove extra charset setting in EditorConfig.

desktop/app.js
Issue #497 
"Auto-lock on minimize" should probably also lock on hide
=> "Auto-lock on minimize" also lock on hide 

app/scripts/views/details/details-history-view.js
This PR will fix a small typo in the `DetailsHistoryView`.
=> fix(DetailsHistoryView): small typo

app/scripts/helpers/add.js, app/scripts/helpers/index.js, app/scripts/views/open-view.js, app/styles/areas/_open.scss, app/templates/open.hbs, package.json
Enhancement/fix for issue ["Keyboard accessibility needs a little help #399"](https://github.com/keeweb/keeweb/issues/399)
- add tabindex to labels on opening screen and listen to keydown event to trigger same functionality as onclick.
- add handlebar helper to support addition to be able to set tabindex from iteration index plus some starting number.
- apply consistent action-color for focus on labels and icons
- add dev script to package.json
=> Keyboard Accessibility on open screen

README.md
Fixes a broken link in the README.md
=> Fix broken "Help Wanted" link

app/scripts/comp/key-handler.js, app/scripts/models/menu/menu-model.js, app/scripts/views/menu/menu-view.js
Added shortcuts Action+Opt+Up/Down to navigate menu.
=> Added shortcuts Action+Opt+Up/Down to navigate menu

app/scripts/views/settings/settings-view.js
@antelle This line was obviously there for a reason, please have a look. The app works without that line, though, and the issue is fixed.
=> Removed invalid (?) sanity check to fix #904

app/scripts/mixins/copyable.js, app/scripts/views/details/details-history-view.js, app/scripts/views/details/details-view.js
@antelle I duplicated code for this (from DetailsView to DetailsHistoryView). Please check, if it would be possible to concentrate the code somewhere. I first thought, DetailsHistoryView would extend DetailsView, but it doesn't.
=> Added tooltip when field from history was copied. Fixes #857

app/scripts/locales/base.json, app/scripts/locales/de-DE.json, app/scripts/locales/fr-FR.json, app/scripts/storage/storage-file.js, app/scripts/views/settings/settings-file-view.js
=> Better error message, when backup path is a directory and not a file

desktop/app.js
Issue #954: If a display is disconnected while KeeWeb is minimized,
when the window position is restored (either during the same session
or after quitting and restarting KeeWeb) it will typically be positioned
where the now disconnected display used to be, making it difficult
for the user to find the window and reposition it to a connected display.
This commit makes KeeWeb check whenever the window position is restored
to be sure there is enough of the title bar on some connected display
that the user can find and drag the window. If there is not, the window
is repositioned to the primary display.
I've been able to test this only on Windows 7, using one and two monitors.
=> always-restore-to-a-connected-monitor (addresses Issue #954)

app/scripts/views/icon-select-view.js
Is it only me getting this error? I'am using eslint 5.14.1 (linux)
=> icon-select-view.js: remove unused Launcher (eslint:app)

app/scripts/models/app-model.js, app/scripts/models/entry-model.js, app/scripts/util/comparators.js
Fixes the issue, that came up in #1073 after merging
=> Lowercased the search string, so case doesn't produce different ranking results

app/scripts/models/app-model.js
=> Fixed missing preparation for filter on autotype

app/scripts/comp/copy-paste.js, app/scripts/locales/base.json, app/scripts/models/app-settings-model.js, app/scripts/util/tip.js, app/scripts/views/details/details-view.js, app/scripts/views/fields/field-view.js, app/scripts/views/generator-view.js, app/styles/areas/_generator.scss, app/templates/generator.hbs
=> Option to hide password in generator

package/docker/entrypoint.sh
Thanks for taking the time to contribute! :gift:
Please follow these steps:
1. work on the right branch: it must be `develop` for new features and `master` for hotfixes
2. make sure the feature you add is not listed in [banned features](https://github.com/keeweb/keeweb/wiki/Unsupported-Features)
3. check compatibility with [the project roadmap](https://github.com/keeweb/keeweb/wiki/TODO) and key features: you should not break anything
4. if your feature is introducing a lot of new UI or changing any UX or design concept, please open an issue to discuss it first
5. please respect existing style in code, styles, and markup (hint: install and enable [editorconfig](http://editorconfig.org/) in your editor)
6. don't add any dependencies
7. test your code: it must work in all browsers, Windows, …
=> Make docker image customizable

app/scripts/util/generators/password-generator.js
This will remove the "binning" from password generation, therefore increasing the entropy. Generated passwords will no longer necessarily have an equal number of characters from each selected set.
=> Remove "binning" from password generation

app/scripts/comp/launcher/index.js, app/scripts/comp/launcher/launcher-cordova.js, app/scripts/views/open-view.js
Hi! Long time no see.
I'm updating mobile build to latest cordova version, thought also to update integration code.
I use it continuously on my phone, it works..
Changes:
- Uncommented cordova launcher
- Removed [this condition](https://github.com/keeweb/keeweb/blob/master/app/scripts/views/open-view.js#L923). It's no longer needed.
- Aligned functions with electron launcher.
=> Update cordova launcher, remove unnecessary code.

app/scripts/models/entry-model.js
=> fix #1395 - advanced search will cause a typeerror

app/scripts/auto-type/index.js
If statement didn't check for support for window id, was causing issues on linux.
=> Added check for system supporting window id

package/docker/Dockerfile
This will make the image smaller
=> Clean up apt local cache in Dockerfile

package/docker-rpi/Dockerfile
This will make the image smaller
=> Ask apk to leave no cache in Dockerfile

desktop/scripts/util/browser-extension-installer.js
I've recently switched from Google Chrome to Google Chrome Dev (Linux), and found that KeeWeb Connect extension is constantly showing error while connecting to the standalone application.
After several hours of debugging I discovered that Chrome Dev is searching for NativeMessaging config files in a different location - `~/.config/google-chrome-dev/NativeMessagingHosts` instead of `~/.config/google-chrome/NativeMessagingHosts`.
Possible locations are described here:
https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host-location
https://www.chromium.org/getting-involved/dev-channel
So I've added all of them into the application. Now activating Chrome checkbox will install NativeMessaging for Dev/Beta/Canary/Unstable versions, as well as Chromium.
This should fix …
=> Install NativeMessagingHost for Chromium and Chrome dev/canary

desktop/scripts/util/browser-extension-installer.js
Quick fix for eslint\prettier error (#1964) during desktop build on developer branch.
No new functionality, only code styling issues.
=> Fix prettier (#1964)

app/scripts/views/details/details-view.js, app/templates/details/details.hbs
Fixed a couple of spots missing localization when an entry had no title.
=> Fixed missing localization of no title
